import { IStreamCard } from 'lib/model/StreamCard';
import { v4 } from 'uuid';
import Thumb1 from 'asset/content/realtime_hotissue_1.jpeg';
import ProfileImageSample from 'asset/content/realtime_hotissue_thumb_1.jpeg';

export const DummyStreamCard: IStreamCard[] = [
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: true,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: false,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '아이스아메리카노',
        viewCount: 100,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: true,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '딸기라떼',
        viewCount: 200,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: false,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: true,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: false,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: true,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: false,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: true,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
    {
        id: v4(),
        thumbnailUrl: Thumb1,
        isAllowToExplore: false,
        title: '신입롤여캠 금이루 새해의 솔랭 ㅇ_< !! (맞즐 [괴인협회]',
        profileImageUrl: ProfileImageSample,
        nickName: '서금이',
        viewCount: 11,
        startDate: '2022-12-31T15:01',
    },
];
